#!/usr/bin/perl
# This program is free software. You can redistribute it and/or modify it under
# the same terms as perl itself.
# Copyright © M. Kristall
use strict;

my $cmd;
my %EXEC;
$SIG{CHLD} = sub {
	my $pid = waitpid (-1, 0);
	return unless (exists ($EXEC{$pid}));
	my $status = $? >> 8;
	warn ("$EXEC{$pid} exited with status $status\n") if ($status);
	delete ($EXEC{$pid});
};

sub run (@) {
	my $pid;
	unless ($pid = fork) {
		# prevent warning
		die ("exec @_ - $!\n") unless (exec (@_));
	}
	$EXEC{$pid} = [@_];
}

vec (my $v = '', fileno (STDIN), 1);
sub prompt () {
	my $r;
	return !system ($cmd) if ($cmd);
	do {
		print 'Did things work (y/n)? ';
		STDOUT->flush;
		chomp ($r = lc (<STDIN>));
	} while ($r ne 'y' && $r ne 'n');
	$r eq 'y';
}

sub readconf ($$) {
	my ($obj, $lines) = @_;
	while (my $line = $obj->getitem) {
		push (@$lines, $line);
	}
	$obj->close;
}

sub writeconf ($$$$) {
	my ($file, $lines, $start, $end) = @_;
	die ("open '$file': $!\n") unless (open (my $fh, '>', $file));
	for (my $i = $start; $i <= $end; $i++) {
		print $fh $$lines[$i]->value;
	}
	close ($fh);
}

sub bisect ($$@) {
	my ($file, $lines, @cmd) = @_;
	my $low = 0;
	my $high = @$lines;
	while ($low < $high) {
		my $mid = $low + int (($high - $low) / 2);
		try:
		writeconf ($file, $lines, $low, $mid);
		run (@cmd) if (@cmd);
		# not this part
		if (prompt) {
			$low = $mid + 1;
		} else {
			$high = $mid;
		}
		if (%EXEC) {
			local $| = 1;
			print 'Waiting for ',
				join (', ', map { "\"$$_[0]\"" } values (%EXEC));
			sleep (1) while (%EXEC);
			print "\n";
		}
	}
	$low;
}

my $OBJ;
$SIG{INT} = sub {
	$OBJ->restore if ($OBJ);
	die ("Caught interrupt\n");
};

sub bifind ($@) {
	my ($obj, @cmd) = @_;
	my @lines;
	readconf ($obj, \@lines);
	$obj->backup;
	my $n = bisect ($obj->file, \@lines, @cmd);
	$obj->restore;
	die ("error line not found\n") if ($n < 0 || $n > $#lines);
	print 'Found error ', $obj->file, ':',
		$lines[$n]->line, " $lines[$n]";
}

# add various command line options
my %opts = (
	type => 'Line',
	'sh-comment' => 1,
	'c-comment' => 1,
	'cpp-comment' => 1
);
my @args;
foreach (@ARGV) {
	if (/^--(\w+)(?:=(.*))?$/) {
		$opts{$1} = $2;
	} else {
		push (@args, $_);
	}
}

$cmd = delete ($opts{run});
my ($file, @cmd) = @args;
my $pkg = $opts{type};
die ("require $pkg: ", $@ || $!, "\n") unless (do ("$pkg.pm"));
$OBJ = $pkg->new ($file, %opts);
bifind ($OBJ, @cmd) if ($file); #XXX
